python27:
  image: python:2.7
  script:
   - pip install pytest
   - python -m pytest junit2htmlreport

python36:
  image: python:3.6
  script: 
   - pip install pytest
   - python -m pytest junit2htmlreport
